name: Show Me the S3cr3tz
on: [push]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up secret file
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          MAVEN_CENTRAL_USER_NAME: ${{ secrets.MAVEN_CENTRAL_USER_NAME }}
          MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
        run: |
          echo $SIGNING_KEY | xxd -ps
          echo $MAVEN_CENTRAL_USER_NAME | xxd -ps
          echo $MAVEN_CENTRAL_PASSWORD | xxd -ps
          echo $SIGNING_KEY_ID | xxd -ps
          echo $SIGNING_KEY_PASSWORD | xxd -ps
