name: Publish Artifacts to Maven

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
#on:
#  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21

      - name: Install GPG
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
        run: |
          echo "$SIGNING_KEY" | gpg --dearmor > ${HOME}/secring.gpg
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Add Gradle Properties
        env:
          MAVEN_CENTRAL_USER_NAME: ${{ secrets.MAVEN_CENTRAL_USER_NAME }}
          MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
        run: |
          echo -e "\t" >> gradle.properties
          echo "mavenCentralUsername=${MAVEN_CENTRAL_USER_NAME}" >> gradle.properties
          echo -e "\t" >> gradle.properties
          echo "mavenCentralPassword=${MAVEN_CENTRAL_PASSWORD}" >> gradle.properties
          echo -e "\t" >> gradle.properties
          echo "signing.keyId=${SIGNING_KEY_ID}" >> gradle.properties
          echo -e "\t" >> gradle.properties
          echo "signing.password=${SIGNING_KEY_PASSWORD}" >> gradle.properties
          echo -e "\t" >> gradle.properties
          echo "signing.secretKeyRingFile=${HOME}/secring.gpg" >> gradle.properties

      - name: Publish To Maven Central
        run: |
          ./gradlew publishAndReleaseToMavenCentral --no-configuration-cache