on:
  push:
    tags:
      - 'c[0-9]+.[0-9]+.[0-9]+'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  BuildBinaries:
    name: Build application packages
    strategy:
      matrix:
        runtime: [ linux-x64, osx-x64, win-x64, android ]
        include:
          - runtime: linux-x64
            arch: x64
            os: ubuntu-latest
            build: cbtApp:packageReleaseUberJarForCurrentOS cbtApp:packageDeb

          - runtime: osx-x64
            os: macOS-latest
            build: cbtApp:packageUberJarForCurrentOS cbtApp:packageDmg

          - runtime: win-x64
            os: windows-latest
            build: cbtApp:packageReleaseUberJarForCurrentOS cbtApp:packageReleaseMsi

          - runtime: android
            os: ubuntu-latest
            build: cbtApp:assembleRelease

    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        if: ${{ matrix.runtime != 'linux-fedora-x64' }}
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        if: ${{ matrix.runtime == 'android' }}

      - name: Setup build tool version variable
        shell: bash
        run: |
          BUILD_TOOL_VERSION=$(ls /usr/local/lib/android/sdk/build-tools/ | tail -n 1)
          echo "BUILD_TOOL_VERSION=$BUILD_TOOL_VERSION" >> $GITHUB_ENV
          echo Last build tool version is: $BUILD_TOOL_VERSION
        if: ${{ matrix.runtime == 'android' }}

      - name: Accept Android licenses
        run: yes | "$ANDROID_HOME"/cmdline-tools/latest/bin/sdkmanager --licenses || true
        if: ${{ matrix.runtime == 'android' }}

      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: >
            ${{ matrix.build }}

      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        if: ${{ matrix.runtime == 'android' }}
        with:
          releaseDirectory: cbtApp/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: ${{ env.BUILD_TOOL_VERSION }}

      # Upload runner package tar.gz/zip as artifact
      - name: Publish Artifact
        uses: actions/upload-artifact@v3
        with:
          name: runner-package-${{ matrix.runtime }}
          path: |
            cbtApp/build/compose/binaries/main/*/
            cbtApp/build/compose/binaries/main-release/*/
            cbtApp/build/compose/jars/
            !cbtApp/build/compose/binaries/main/app/
            ${{ env.SIGNED_RELEASE_FILE }}

        # Upload runner errors
      - name: Upload error logs
        uses: actions/upload-artifact@v3
        if: ${{ failure() }}
        with:
          name: runner-errors-${{ matrix.runtime }}
          path: |
            cbtApp/build/compose/logs/
  ReleaseBinaries:
    name: Make a release
    needs: [ BuildBinaries ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download Build Artifacts
        uses: actions/download-artifact@v3

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "*/binaries/main/*/*.*,*/binaries/main-release/*/*.*,*/jars/*.jar,*/app/build/outputs/apk/release/*.apk"
          draft: true
          token: ${{ secrets.TOKEN }}